# Generated by Django 5.0.2 on 2024-03-25 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_genre_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_Name', models.CharField(max_length=50, unique=True)),
                ('Book_image', models.FileField(upload_to='images')),
                ('status', models.BooleanField(default=True)),
                ('genre_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.genre')),
            ],
        ),
    ]
