# Generated by Django 5.0.2 on 2024-03-26 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Book_image',
        ),
    ]
