# Generated by Django 5.0.2 on 2024-04-16 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_room_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='first_user',
            field=models.ForeignKey(db_column='user_1', on_delete=django.db.models.deletion.CASCADE, related_name='user_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='room',
            name='second_user',
            field=models.ForeignKey(db_column='user_2', on_delete=django.db.models.deletion.CASCADE, related_name='user_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
