# Generated by Django 5.0.2 on 2024-04-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_room_first_user_alter_room_second_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Plan_Name', models.CharField(max_length=20, unique=True)),
                ('validity', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
