# Generated by Django 5.0.2 on 2024-04-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='Plan_Name',
            field=models.CharField(max_length=20),
        ),
    ]
