# Generated by Django 5.0.2 on 2024-05-07 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_book_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_views',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
