from django.urls import path
from .views import *


urlpatterns = [
    path('login/', UserLoginView.as_view(), name='user_login'),
    path('register/', UserRegistrationView.as_view(), name='user_registration'),
    path('admin_login/', AdminLoginView.as_view(), name='admin_login'),
    path('user_list/', UserListAPIView.as_view(), name='user_list'),
    path('user_list/<int:id>', UserListAPIView.as_view(), name='user_list'),
    path('check_email/', CheckEmail.as_view(), name='check_email'),
    path('send_otp_email/', OtpMail.as_view(), name='send_otp_email'),
    path('genre/', Genres.as_view(), name='genre'),
    path('genre/<int:pk>/', Genres.as_view(), name='genre'),
    path('users/<int:id>/', UserList.as_view(), name='users'),
    path('users/<str:type>/', UserList.as_view(), name='users'),
    path('book/', Books.as_view(), name='book'),
    path('books/', ViewBook.as_view(), name='book'),
    path('book/<int:author_id>/', Books.as_view(), name='book'),
    path('books/<int:pk>/', Books.as_view(), name='book'),
    path('review/', Reviews.as_view(), name='review'),
    path('review/<int:id>', Reviews.as_view(), name='review'),
    path('reviews/<int:user_id>/', ViewReviews.as_view(), name='reviews'),
    path('author_reviews/<int:id>/', AuthorReviews.as_view(), name='author_reviews'),
    path('admin_reviews/', AdminReviews.as_view(), name='admin_reviews'),
    path('admin_reviews/<int:id>/', AdminReviews.as_view(), name='admin_reviews'),
    path('view_post/<int:id>/', View_Post.as_view(), name='view_post'),
    path('like/', Like.as_view(), name='like'),
    path('comment/', Comment.as_view(), name='comment'),
    path('comment/<int:id>/', Comment.as_view(), name='comment'),
    path('room/', Rooms.as_view(), name='room'),
    path('chat_user/<int:id>', ChatUser.as_view(), name='chat_user'),
    path('plan/', Plans.as_view(), name='plan'),
    path('plan/<int:id>', Plans.as_view(), name='plan'),
    path('pay/', PaymentView.as_view(), name='pay'),
    path('upcoming/', View_Upcoming.as_view(), name='upcoming'),
    path('post_upcoming/', Upcomings.as_view(), name='upcoming'),
    path('upcoming/<int:pk>/', Upcomings.as_view(), name='upcoming'),
    path('upcomings/<int:pk>/', Upcomings.as_view(), name='upcoming'),
    path('top_reviews/', Top_Reviews.as_view(), name='top_reviews'),
    path('user_home/', User_Home.as_view(), name='user_home'),
    path('profile/', Profile.as_view(), name='profile'),
    path('admin_home/', Admin_Home.as_view(), name='admin_home'),
    path('check/<int:id>', Premium_User.as_view(), name='check'),
    path('message/', Messages.as_view(), name='message'),
    path('message/<int:id>', Messages.as_view(), name='message'),
    path('view_book/<int:id>', View_Book.as_view(), name='view_book'),
    path('book_like/', Book_Likes.as_view(), name='book_like'),
]